"""
Django settings for dani_site project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dani_site.local_settings import DATABASE_PASSWORD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-na9ft$3fjkww^l7wjz-&q2q!l=9#otd4i_+73s3**^$^4%h^sc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# SITE_ID = 1

# AUTHENTICATION_BACKENDS = [

#     'django.contrib.auth.backends.ModelBackend', 
#     'allauth.account.auth_backends.AuthenticationBackend',
                           
# ]

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# AUTHENTICATION_BACKENDS = [
#     # ... other backends
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.account.auth_backends.AuthenticationBackend',
#     'allauth.socialaccount.auth_backends.SocialAccountAuthBackend',
# ]


SOCIALAUTH_FACEBOOK_KEY = 'YOUR_FACEBOOK_APP_ID'
SOCIALAUTH_FACEBOOK_SECRET = 'YOUR_FACEBOOK_APP_SECRET'
# SOCIALAUTH_FACEBOOK_SCOPE = ['email']  # Request additional user data (optional)
SOCIALAUTH_FACEBOOK_AUTH_URL = 'https://www.facebook.com/dialog/oauth'  # Facebook authentication URL

# SOCIALAUTH_LOGIN_REDIRECT_URL = '/'  # Redirect URL after login
# SOCIALAUTH_LOGOUT_REDIRECT_URL = '/'  # Redirect URL after logout


EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '45c1663876cb82'
EMAIL_HOST_PASSWORD = '********42c6'
EMAIL_PORT = '2525'
EMAIL_USE_TLS = True

# Application definition

INSTALLED_APPS = [
    'twomodels',
    'accounts',
    'cv',
    'base',
    'pages',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',

    'allauth',
    'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.github',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'dani_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'pages.context_processors.my_context_processor',  # Replace with your app's name
                # 'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request', 
            ],
        },
    },
]


# SOCIALACCOUNT_PROVIDERS = {
#     'github':{
#         'APP':{

#             'client_id':'125',
#             'secret': '456',
#             'key':''
#         }
#     }
# }

WSGI_APPLICATION = 'dani_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME' : 'db_dani',
#         'USER' : 'dani_user',
#         'PASSWORD': DATABASE_PASSWORD,
#         'HOST' : 'localhost',
#         'PORT' : '3307',
#     }
# }


DATABASES = {
'default': {
'ENGINE': 'django.db.backends.sqlite3',
'NAME': BASE_DIR / 'db.sqlite3',
}
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



STATIC_URL = 'static/'


MEDIA_URL = '/media/'  # Replace with your actual media URL if different
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Replace BASE_DIR with your project's base directory



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'accounts:profile'
LOGOUT_REDIRECT_URL = 'login'







