# Generated by Django 5.0.6 on 2024-05-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twomodels', '0003_developer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
