# Generated by Django 5.0.6 on 2024-05-20 08:42

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(default=pages.models.current_datetime),
        ),
    ]
