# Generated by Django 5.0.6 on 2024-05-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
