# Generated by Django 5.0.3 on 2024-05-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='created_at',
            new_name='done_at',
        ),
    ]
